python simulate.py \
    --md-param-key vital-cosmos-120 \
    --md-param-step 144 \
    --directory-path "/home/yxwu/pGM_water_model/wandb_data/vital-cosmos-120" \
    --md-config.output-dir /home/yxwu/pGM_water_model/MD_data/langevin_Berendsen \
    --md-config.case case_1 \
    --md-config.md-lengths "10step" "10step" "1step" \
    --md-config.use-custom-case-folder-name \
    --md-config.custom-case-folder-name vital-cosmos-120_144 \
    --md-config.thermostat langevin \
    --md-config.barostat Berendsen \
    --md-config.pipeline-name nvt-npt-dipole \
    --slurm.mode slurm \
    --slurm.slurm-job-name vital-cosmos-120_144 \
    --slurm.slurm-partition "cpu" \
    --slurm.slurm-output-folder "/home/yxwu/pGM_water_model/MD_data/vital-cosmos-120_144/slurm" \
    --slurm.cpus-per-task 8 \