keys_list = {
    "npt": [
        "NSTEP",
        "TIME(PS)",
        "TEMP(K)",
        "PRESS",
        "Etot",
        "EKtot",
        "EPtot",
        "BOND",
        "ANGLE",
        "DIHED",
        "1-4 NB",
        "1-4 EEL",
        "VDWAALS",
        "EELEC",
        "EHBOND",
        "RESTRAINT",
        "EKCMT",
        "VIRIAL",
        "VOLUME",
        "EPOLZ",
        "Density",
        "Ewald error estimate",
    ],
    "nve": [
        "NSTEP",
        "TIME(PS)",
        "TEMP(K)",
        "PRESS",
        "Etot",
        "EKtot",
        "EPtot",
        "BOND",
        "ANGLE",
        "DIHED",
        "1-4 NB",
        "1-4 EEL",
        "VDWAALS",
        "EELEC",
        "EHBOND",
        "RESTRAINT",
        "EPOLZ",
        "Ewald error estimate",
    ],
    "nvt": [
        "NSTEP",
        "TIME(PS)",
        "TEMP(K)",
        "PRESS",
        "Etot",
        "EKtot",
        "EPtot",
        "BOND",
        "ANGLE",
        "DIHED",
        "1-4 NB",
        "1-4 EEL",
        "VDWAALS",
        "EELEC",
        "EHBOND",
        "RESTRAINT",
        "EPOLZ",
        "Ewald error estimate",
    ],
}
